name: "Backup CosmosDB to Azure Storage"
description: "Backs up a CosmosDB instance to a Storage Account using Azure CLI"
inputs:
  azure-credentials:
    description: 'Azure credentials in JSON format'
    required: true
  azure-client-id:
    description: 'Azure Client ID'
    required: true
  azure-tenant-id:
    description: 'Azure Tenant ID'
    required: true
  azure-subscription-id:
    description: 'Azure Subscription ID'
    required: true
  azure-client-secret:
    description: 'Azure Client Secret'
    required: true
  cosmos-endpoint:
    description: 'Endpoint of the CosmosDB account'
    required: true
  cosmos-account:
    description: 'Name of the CosmosDB account'
    required: true
  cosmos-key:
    description: 'Access key for CosmosDB'
    required: true
  cosmos-db:
    description: 'Name of the database'
    required: true
  cosmos-container:
    description: 'Name of the container'
    required: true
  resource-group:
    description: 'Resource group of the CosmosDB'
    required: true
  storage-account:
    description: 'Name of the Storage Account'
    required: true
  container-name:
    description: 'Name of the container in the Storage Account'
    required: true
  action:
    description: 'Action to perform: backup or restore'
    required: true
    default: 'backup'
    options:
      - backup
      - restore

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - uses: azure/login@v2
      with:
        creds: ${{ inputs.azure-credentials }}
        

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Run Python script
      run: |
        export COSMOS_KEY="${{ inputs.cosmos-key }}"
        export COSMOS_ENDPOINT="${{ inputs.cosmos-endpoint }}"
        export CONTAINER_NAME="${{ inputs.cosmos-container }}"
        export DATABASE_NAME="${{ inputs.cosmos-db }}"
        export RESOURCE_GROUP="${{ inputs.resource-group }}"
        export STORAGE_ACCOUNT_NAME="${{ inputs.storage-account }}"
        export STORAGE_CONTAINER="${{ inputs.container-name }}"
        export SUBSCRIPTION_ID="${{ inputs.azure-subscription-id }}"
        export ARM_CLIENT_ID="${{ inputs.azure-client-id }}"
        export ARM_CLIENT_SECRET="${{ inputs.azure-client-secret }}"
        export ARM_SUBSCRIPTION_ID="${{ inputs.azure-subscription-id }}"
        export ARM_TENANT_ID="${{ inputs.azure-tenant-id }}"

        echo "Iniciando Job de backup"
        python ${{ github.action_path }}/"${{ inputs.action }}".py 

        OUTPUT_FILE=$(find . -type f -name "cosmosdb_nosql_backup_*.json" | sort | tail -n 1)
        if [ -f "$OUTPUT_FILE" ]; then
          echo "output-file=$OUTPUT_FILE" >> $GITHUB_ENV
        else
          echo "Error: Output file not found!"
          exit 1
        fi
      shell: bash

    - name: Upload file to Azure Storage
      if: ${{ inputs.action == 'backup' }}
      run: |
        az storage blob upload \
              --account-name ${{ inputs.storage-account }} \
              --container-name ${{ inputs.container-name }} \
              --file "$OUTPUT_FILE" \
              --name "$(basename "$OUTPUT_FILE")" \
              --auth-mode login
      shell: bash
