name: Backup CosmosDB

on:
  workflow_dispatch:
  # this workflow will be triggered by the cron job helm chart
  # the cron job helm chart will be used to schedule the backup
  schedule:
    - cron: "0 2 * * *" # Every day at 2 AM UTC
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Backup CosmosDB to Azure Storage
        uses: ./.github/actions/cosmosdb-backup
        with:
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          cosmos-account: "https://cosmos-cosmosdb-account.documents.azure.com:443/"
          cosmos-key: ${{ secrets.COSMOS_KEY }}
          cosmos-db: "cosmos-database"
          cosmos-container: "cosmosbkp1123"
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resource-group: "cosmos-resources"
          storage-account: "cosmosbkp1123"
          container-name: "osmos-backup-container"
          action: "backup" # action should be backup or restore
