name : 🌌 Backup and Restore CosmosDB

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # Every day at 2 AM UTC
  push:
    branches:
      - main

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Restore CosmosDB from Azure Storage
        uses: ./.github/actions/cosmosdb-restore
        with:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          COSMOS_DB_SOURCE_ACCOUNT: "cosmos-cosmosdb-account"
          COSMOS_ENDPOINT: "https://cosmos-cosmosdb-account-restore.documents.azure.com:443"
          COSMOS_KEY: ${{ secrets.RESTORE_KEY }}
          RESOURCE_GROUP: "cosmos-resources"
          STORAGE_ACCOUNT_NAME: "cosmosbkp1123"
          STORAGE_CONTAINER: "cosmos-backup-container"
          TIMESTAMP:  "2025-05-05-2127"
          action: "full_restore"